### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by cytommi** [bytecodealliance/spidermonkey-wasm-rs#34]
Firstly, thank you for the wonderful work. I'm very interested in the project and would love to explore its potential use case for a project. 

As I am a rust novice myself (please bear with me!), I was wondering if anyone could kindly update the README with more details/instructions for the project? Thank you in advance!

**Comment by saulecabrera** [comment]
Hi @cytommi -- updating the README with better instructions is definitely something that is on my todo list, I haven't gotten to it mostly because of competing priorities and because the project has been under development; in https://github.com/bytecodealliance/spidermonkey-wasm-rs/pull/28 I introduced a complete example on how to build a [JS REPL](https://github.com/bytecodealliance/spidermonkey-wasm-rs/blob/main/crates/repl-example/src/main.rs), is that the kind of instructions/details that you're looking for?

**Comment by cytommi** [comment]
Thank you for the swift response! For me at least, I'm having a little trouble bridging the gap between this [article](https://bytecodealliance.org/articles/making-javascript-run-fast-on-webassembly) and actually running JS in WASM through this repo. I think my lack of rust knowledge is blocking me from using/contributing to this repo now.

Definitely understand that you have competing priorities -- I'll be on the look out for more detailed guides. I'll enhance my rust knowledge in the meantime :) Thanks again!
